#!/usr/bin/env python3
"""Generate emails-production/ — the emails with absolute HTTPS asset URLs,
ready to paste into an ESP.

    python3 build-production.py [BASE_URL]

The preview keeps using relative paths and is unaffected. Re-run this whenever
you change an email or move the asset host.
"""
import os, re, sys, glob, shutil

BASE = (sys.argv[1] if len(sys.argv) > 1
        else "https://tdethomaz10.github.io/delstudio-emails").rstrip("/")

ROOT = os.path.dirname(os.path.abspath(__file__))
os.chdir(ROOT)
OUT = "emails-production"
shutil.rmtree(OUT, ignore_errors=True)
os.makedirs(OUT)

banner = f"""<!--
  ============================================================================
  PRODUCTION COPY — asset URLs point at {BASE}
  ----------------------------------------------------------------------------
  Generated by build-production.py. Do not hand-edit; edit the file in
  emails/ and re-run the script.

  Before sending, still fill in:
    {{{{FirstName}}}}       your ESP's first-name merge tag
    {{{{BOOKING_URL}}}}     the scheduling link
    {{{{GUIDE_URL}}}}       {BASE}/assets/docs/renovation-process-guide.pdf
    {{{{UnsubscribeURL}}}}  your ESP's unsubscribe tag
  ============================================================================
-->
"""

count = 0
for src in sorted(glob.glob("emails/*.html")):
    s = open(src, encoding="utf8").read()
    s = s.replace('"../assets/', f'"{BASE}/assets/')
    s = s.replace("'../assets/", f"'{BASE}/assets/")
    s = s.replace("url(../assets/", f"url({BASE}/assets/")
    s = s.replace("</head>", banner + "</head>", 1)
    dst = os.path.join(OUT, os.path.basename(src))
    open(dst, "w", encoding="utf8").write(s)
    left = len(re.findall(r'\.\./assets/', s))
    print(f"  {os.path.basename(src):34s} {'OK' if left == 0 else f'{left} RELATIVE LEFT'}")
    count += 1

print(f"\n{count} emails → {OUT}/   base: {BASE}")
