#!/usr/bin/env python3
"""Generate emails-ghl/ — the emails ready to paste into GoHighLevel.

    python3 build-ghl.py

Three things differ from emails/:
  1. Asset URLs are absolute HTTPS. Relative paths CANNOT work in an email —
     there is no page for them to be relative to.
  2. Placeholder tokens are resolved. {{BOOKING_URL}} and {{GUIDE_URL}} were
     never merge fields; they were slots for real URLs. Left in place, the
     href is literally "{{GUIDE_URL}}" and the link 404s.
  3. Personalisation uses GoHighLevel syntax: {{contact.first_name}}.

Edit the CONFIG block, then re-run.
"""
import os, re, sys, glob, shutil

# ── CONFIG ────────────────────────────────────────────────────────────────
ASSET_BASE  = "https://tdethomaz10.github.io/delstudio-emails"
BOOKING_URL = "https://delstudioarchitects.com/contact/"          # <-- your Calendly when ready
GUIDE_URL   = f"{ASSET_BASE}/assets/docs/renovation-process-guide.pdf"
FIRST_NAME  = "{{contact.first_name}}"                            # GoHighLevel merge field
UNSUB       = "{{unsubscribe_link}}"                              # VERIFY in GHL's picker
# ──────────────────────────────────────────────────────────────────────────

ROOT = os.path.dirname(os.path.abspath(__file__)); os.chdir(ROOT)
OUT  = "emails-ghl"
shutil.rmtree(OUT, ignore_errors=True); os.makedirs(OUT)

REPLACEMENTS = [
    ('"../assets/',      f'"{ASSET_BASE}/assets/'),
    ("'../assets/",      f"'{ASSET_BASE}/assets/"),
    ("url(../assets/",   f"url({ASSET_BASE}/assets/"),
    ("{{FirstName}}",     FIRST_NAME),
    ("{{BOOKING_URL}}",   BOOKING_URL),
    ("{{GUIDE_URL}}",     GUIDE_URL),
    ("{{UnsubscribeURL}}", UNSUB),
]

banner = f"""<!--
  ============================================================================
  GOHIGHLEVEL BUILD — generated by build-ghl.py, do not hand-edit.
  Edit emails/ and re-run the script.

  Resolved for this build:
    asset host      {ASSET_BASE}/assets/
    booking link    {BOOKING_URL}
    guide PDF       {GUIDE_URL}
    personalisation {FIRST_NAME}
    unsubscribe     {UNSUB}   <-- VERIFY with GHL's merge-field picker

  PASTE INTO: Marketing > Emails > new template > blank > add a CODE / HTML
  element and paste the whole file. Do NOT paste into a rich-text block —
  it strips the table layout.
  ============================================================================
-->
"""

problems = 0
for src in sorted(glob.glob("emails/*.html")):
    s = open(src, encoding="utf8").read()
    for a, b in REPLACEMENTS:
        s = s.replace(a, b)
    s = s.replace("</head>", banner + "</head>", 1)
    name = os.path.basename(src)
    open(os.path.join(OUT, name), "w", encoding="utf8").write(s)

    rel   = len(re.findall(r'\.\./assets/', s))
    left  = set(re.findall(r'\{\{(?!contact\.|unsubscribe_link)[A-Za-z_]+\}\}', s))
    status = "OK"
    if rel or left:
        problems += 1
        status = f"{rel} relative" + (f" · unresolved {sorted(left)}" if left else "")
    print(f"  {name:32s} {status}")

print(f"\n{len(glob.glob(OUT+'/*.html'))} files -> {OUT}/")
print("problems:", problems)
